### ISSUE TITLE
Bug virtual world in 0.3.7 client

### ISSUE THREAD

**Issue by energizer1337** [AGraber/samp-037-compat#2] opened 2018-05-16 19:27 UTC
The essence of the bug, if you go to the server from the client 0.3.7 and go to another virtual world together with other players, then you will not see them, only the markers on the map will be visible.

**Comment by energizer1337** [comment] 2018-05-16 20:10
The bug is caused if the server has a cache that the player must download.

**Comment by Romz24** [comment] 2018-05-16 20:29
This problem also exists when changing the interior.

**Comment by NaboColosal** [comment] 2018-05-16 23:07
ok

**Comment by AGraber** [comment] 2018-05-17 14:14
This seems to be caused by the [FinishedDownloaing RPC](https://github.com/BrunoBM16/RPC-List/wiki/0.3.DL-Specific-RPCs#finisheddownloading---id-184) which goes missing in virtual world changes, messing up the sync on normal clients. The only way would be by emulating the reception of a packet, which is currently not natively supported in plugins at the moment. The only way I see would be to take an incoming packet and convert it to an internal RPC packet, but I don't know if that would actually work since the packet recieving hook is done on a late stage in Pawn.Raknet.

**Comment by Romz24** [comment] 2018-05-19 07:52
@AGraber Is there any news on the development of the plugin?

**Comment by AGraber** [comment] 2018-05-19 12:28
I'm afraid I can't give a certain time frame since I'm busy with work stuff. Despite that, this is something that will take priority on my SA-MP stuff.

**Comment by Romz24** [comment] 2018-05-19 13:11
@AGraber if it is a plugin, can you change the name of the version or add a function so that you can change it yourself? 
![image](https://user-images.githubusercontent.com/2458113/40268924-3777d0f2-5b7f-11e8-814f-af1cdbe52399.png)

**Comment by AGraber** [comment] 2018-06-29 13:32
I'm working on a quick plugin fix that would hook the function on the Pawn side for 0.3.7 players.

**Comment by AGraber** [comment] 2018-07-01 18:30
Fixed in 0495298 thanks to https://github.com/AGraber/samp-037-compat-fix

**Closed by AGraber** 2018-07-01 18:30 UTC
Labels: bug
